# Generated by Django 6.0.8 on 2026-08-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
                ('tipo_comida', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
